const images = {
  ArmenKhojoyan: require("./teamPhotos/ArmenKhojoyan.png"),
  ArmenYesoyan: require("./teamPhotos/ArmenYesoyan.png"),
  SvetlanaMshetsyan: require("./teamPhotos/SvetlanaMshetsyan.jpg"),
  MariamNikoghosyan: require("./teamPhotos/MariamNikoghosyan.png"),
  GurgenBadalyan: require("./teamPhotos/GurgenBadalyan.png"),
  VarduhiManukyan: require("./teamPhotos/VarduhiManukyan.jpg"),
  KhanumAbrahamyan: require("./teamPhotos/KhanumAbrahamyan.png"),
  RubikShahazizyan: require("./teamPhotos/RubikShahazizyan.png"),
  AnushTadevosyan: require("./teamPhotos/AnushTadevosyan.png"),
  DavitNikoghosyan: require("./teamPhotos/DavitNikoghosyan.png"),
  KoryunBznuni: require("./teamPhotos/KoryunBznuni.png"),
  ArmenAjamoghlyan: require("./teamPhotos/ArmenAjamoghlyan.png"),
  TorosTorosyan: require("./teamPhotos/TorosTorosyan.png"),
  MaryMartirosyan: require("./teamPhotos/MaryMartirosyan.jpg"),
  MargaritaGasparyan: require("./teamPhotos/MargaritaGasparyan.png"),
  LiaApikyan: require("./teamPhotos/LiaApikyan.png"),
  MilenaKiramijyan: require("./teamPhotos/MilenaKiramijyan.png"),
  SonaGalstyan: require("./teamPhotos/SonaGalstyan.png"),
  JannaDadiyan: require("./teamPhotos/JannaDadiyan.png"),
  AniTadevosyan: require("./teamPhotos/AniTadevosyan.png"),
  IrmaYuzbashyan: require("./teamPhotos/IrmaYuzbashyan.png"),
  HovhannesKarakhanyan: require("./teamPhotos/HovhannesKarakhanyan.png"),
  ArsenHayrapetyan: require("./teamPhotos/ArsenHayrapetyan.jpg"),
  AlbertArutunian: require("./teamPhotos/AlbertArutunian.png"),
  LianaNersisyan: require("./teamPhotos/LianaNersisyan.png"),
  KarineMovsisyan: require("./teamPhotos/KarineMovsisyan.png"), 
  GogarBuniatyan: require("./teamPhotos/GogarBuniatyan.jpg"),
  MisakHovakimyan: require("./teamPhotos/MisakHovakimyan.jpg"),
  LusineSargsyan: require("./teamPhotos/LusineSargsyan.jpeg"),
  SonaHakobian: require("./teamPhotos/SonaHakobian.jpg"),
  NinaAvagyan: require("./teamPhotos/NinaAvagyan.png"),
  AnnaBarseghyan: require("./teamPhotos/AnnaBarseghyan.jpg"),
  NarineGigolyan: require("./teamPhotos/NarineGigolyan.png"),
};

export default images;
