const images = {
  ArmenKhojoyan: require("./teamPhotos/ArmenKhojoyan.png"),
  ArmenYesoyan: require("./teamPhotos/ArmenYesoyan.png"),
  AniMkrtchyan: require("./teamPhotos/AniMkrtchyan.png"),
  AnjelaManukyan: require("./teamPhotos/AnjelaManukyan.png"),
  GurgenBadalyan: require("./teamPhotos/GurgenBadalyan.png"),
  VarduhiManukyan: require("./teamPhotos/VarduhiManukyan.jpg"),
  KhanumAbrahamyan: require("./teamPhotos/KhanumAbrahamyan.png"),
  RubikShahazizyan: require("./teamPhotos/RubikShahazizyan.png"),
  AnushTadevosyan: require("./teamPhotos/AnushTadevosyan.png"),
  DavitNikoghosyan: require("./teamPhotos/DavitNikoghosyan.png"),
  KoryunBznuni: require("./teamPhotos/KoryunBznuni.png"),
  ArmenAjamoghlyan: require("./teamPhotos/ArmenAjamoghlyan.png"),
  TorosTorosyan: require("./teamPhotos/TorosTorosyan.png"),
  GagikMelkonyan: require("./teamPhotos/GagikMelkonyan.png"),
  MargaritaGasparyan: require("./teamPhotos/MargaritaGasparyan.png"),
  LiaApikyan: require("./teamPhotos/LiaApikyan.png"),
  MilenaKiramijyan: require("./teamPhotos/MilenaKiramijyan.png"),
  SonaGalstyan: require("./teamPhotos/SonaGalstyan.png"),
  JannaDadiyan: require("./teamPhotos/JannaDadiyan.png"),
  AniTadevosyan: require("./teamPhotos/AniTadevosyan.png"),
  IrmaYuzbashyan: require("./teamPhotos/IrmaYuzbashyan.png"),
  HovhannesKarakhanyan: require("./teamPhotos/HovhannesKarakhanyan.png"),
  MikayelVardanyan: require("./teamPhotos/MikayelVardanyan.png"),
  AlbertArutunian: require("./teamPhotos/AlbertArutunian.png"),
  MisakHovakimyan: require("./teamPhotos/MisakHovakimyan.png"),
  LianaNersisyan: require("./teamPhotos/LianaNersisyan.png"),
  KarineMovsisyan: require("./teamPhotos/KarineMovsisyan.png"),
};

export default images;
